### ISSUE TITLE
设计API时，符合行业规范和大家的认知

### ISSUE THREAD

**Issue by weizhiwen** [ximatai/MuYun#7]
![Screenshot_2024-07-25-08-58-22-25.jpg](https://github.com/user-attachments/assets/081cbcd0-2b4a-449f-b536-8f0713800c5b)

另外使用delete请求仅仅通过请求方式就很容易知道这应该是一个删除动作，对于监控和统计各类api的异常调用也是有益的，如果项目为了简化http请求方式的使用，那也应该只使用post请求，get请求也不应该使用，不然仍然会对接口的使用者造成困惑（什么时候我该用get，什么时候我该用post？），delete操作是个get请求？这不符合业界的常识，增加了沟通的成本，并不符合让程序员少加班的宗旨。

**Comment by weizhiwen** [comment]
![Screenshot_2024-07-25-08-58-22-25.jpg](https://github.com/user-attachments/assets/b39565ce-fa6c-44b9-a23b-49e1f5887889)

**Comment by aruis** [comment]
我的设计原则是：
1. URL 是语义化的，不管是GET还是POST，甚至是DELETE请求，URL都要语义化，要能见文知意。
2. 当该项操作需要Body来传输内容的时候，就需要采用POST请求了。所以POST的Body只是对操作内容的补充。在我这里POST跟GET的关系不是互斥的关系，而更是像永远优先GET，GET满足不了传输足量内容的时候，用POST。
3. 其实你完全可以在这里补充一个@Delete 我觉得是合适的，这样也能满足你的诉求了。
https://github.com/aruis/MuYun/blob/dfc452f63467fea85c997e78af08c9bc8ea27325/my-core/src/main/java/net/ximatai/muyun/core/ability/curd/IDeleteAbility.java#L13


最后我还要补充一点，有时候做政府项目的时候，他们的防火墙和安全策略工具压根不允许我们用PUT、DELETE这种HTTP谓词，这个也是实际可能会遇到的情况。

**Comment by weizhiwen** [comment]
HTTP请求也是一种语义化呀，哈哈，政府项目不让用PUT和DELETE有点让人大跌眼镜，所以这种项目统一用POST请求即可，get请求会被客户端缓存，使用get请求最好加上时间戳来避免缓存，有些业务其实根本就不应该有删除的业务，有时其实是禁用

**Comment by aruis** [comment]
get请求被客户端缓存的事，应该不用太在意。因为本来api级别的get响应都会加入no-cache no-store 类似标记，通知浏览器不要缓存。
即使不考虑delete业务，就算是普通的get一条数据，这个请求如果被浏览器缓存了，也会引起一系列的业务问题。所以这个问题一开始我们就会极力避免的。
另外我为什么倾向于用get而不是post：
1. get方便在排查错误的时候，直接在浏览器重现，这个场景我在配合前后端联合调试的时候经常遇到。如果是get请求的话，浏览器端只要F5就能做到秒测，如果是post，就得引入测试工具了，损失了开发效率。
2. get是支持302的，而post请求302后会变成get，这个特性并不友好，甚至会让开发人员困惑。但其实我们的项目是离不开302的，比如你请求一个`/logout`接口，后台在清退用户信息后，就要302到`/index`之类的地方了。

**Comment by weizhiwen** [comment]
直接在浏览器控制台fetch调用接口，不需要api测试工具

**Comment by aruis** [comment]
对，批量删除就是post请求 /delete 了，id们要放在body里面。
这个问题如果你用 delete 谓词的话也会遇到，因为原则上并不鼓励delete请求带body。

**Comment by aruis** [comment]
> 直接在浏览器控制台fetch调用接口，不需要api测试工具

你这句话只能证明这样搞，未必很慢，但是没发证明比我F5快啊。

另外如果我们经常遇到不带body的post，我觉得会很奇怪。这也是违背共识了。

**Comment by TAKETODAY** [comment]
https 能看到内容吗

**Comment by aruis** [comment]
> 防火墙 能看到 https 内容吗 ？

我认为不能，因为防火墙没有SSL的私钥。 @TAKETODAY

**Comment by TAKETODAY** [comment]
> 我的设计原则是：
> 
> 1. URL 是语义化的，不管是GET还是POST，甚至是DELETE请求，URL都要语义化，要能见文知意。
> 2. 当该项操作需要Body来传输内容的时候，就需要采用POST请求了。所以POST的Body只是对操作内容的补充。在我这里POST跟GET的关系不是互斥的关系，而更是像永远优先GET，GET满足不了传输足量内容的时候，用POST。
> 3. 其实你完全可以在这里补充一个@delete 我觉得是合适的，这样也能满足你的诉求了。
>    https://github.com/aruis/MuYun/blob/dfc452f63467fea85c997e78af08c9bc8ea27325/my-core/src/main/java/net/ximatai/muyun/core/ability/curd/IDeleteAbility.java#L12-L15
> 
> 最后我还要补充一点，有时候做政府项目的时候，他们的防火墙和安全策略工具压根不允许我们用PUT、DELETE这种HTTP谓词，这个也是实际可能会遇到的情况。

那这GET，PUT，DELETE 他也读不出来

**Comment by aruis** [comment]
URL 是明文的，HTTPS协议加密只是加密的 body @weizhiwen

**Comment by TAKETODAY** [comment]
> URL 是明文的，HTTPS协议加密只是加密的 body @weizhiwen

不对的 HTTPs 是 TCP 传输层后面多了一层 TLS，整个 HTTP流量都被加密了的

**Comment by aruis** [comment]
是我错了，URL也是被加密的。  @TAKETODAY 
说回前面的话题，我参与的一些政府国企项目，有些在内网，他们也省事，就没上HTTPS。 所以他们还是对我们的HTTP谓词有监控。

**Comment by TAKETODAY** [comment]
> 是我错了，URL也是被加密的。 @TAKETODAY 说回前面的话题，我参与的一些政府国企项目，有些在内网，他们也省事，就没上HTTPS。 所以他们还是对我们的HTTP谓词有监控。

好吧
